# Start the service with the command 'docker-compose up -d'

services:
    psf-bch-api:
      build:
        context: ../..
        dockerfile: production/docker/Dockerfile
      container_name: psf-bch-api
      logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '10'
      #mem_limit: 500mb
      #links:
      #  - mongo-slp-indexer
      ports:
        - '5942:5942' # <host port>:<container port>
      volumes:
        #- ./start-rest2nostr.sh:/home/safeuser/REST2NOSTR/start-rest2nostr.sh
        - ./.env:/home/safeuser/psf-bch-api/.env
        - ../data:/home/safeuser/psf-bch-api/production/data
        - ../data/logs:/home/safeuser/psf-bch-api/logs
      restart: always