# Start the service with the command 'docker-compose up -d'

services:
    psf-bch-api-x402-base:
      build: .
      container_name: psf-bch-api-x402-base
      logging:
        driver: 'json-file'
        options:
          max-size: '10m'
          max-file: '10'
      #mem_limit: 500mb
      #links:
      #  - mongo-slp-indexer
      ports:
        - '6100:6100' # <host port>:<container port>
      volumes:
        #- ./start-rest2nostr.sh:/home/safeuser/REST2NOSTR/start-rest2nostr.sh
        - ./.env:/home/safeuser/.env
        - ../data:/home/safeuser/psf-bch-api-base/production/data
        - ../data/logs:/home/safeuser/psf-bch-api-base/logs
      restart: always

